.PHONY: clean All

All:
	@echo "----------Building project:[ ucpp - Debug ]----------"
	@cd "ucpp" && "$(MAKE)" -f  "ucpp.mk"
clean:
	@echo "----------Cleaning project:[ ucpp - Debug ]----------"
	@cd "ucpp" && "$(MAKE)" -f  "ucpp.mk" clean
